### ISSUE TITLE
add methods create strong references to keys

### ISSUE THREAD

**Issue by mraleph** [marcglasberg/weak_map#1]
Contrary to what documentation says calling `add(key: o, value: ...)` would create a strong reference to the key `o` because it puts it into a map. Meaning that the key would not be GCed unless WeakMap object itself will be GCed. On the other hand values are held weakly through the expando.

Right now it looks like `values` are held weakly but not the keys. 

This means either documentation is wrong or the code is wrong.

**Comment by marcglasberg** [comment]
The Expando documentation is quite bad, but you should know this: The **keys** are weakly held by the Expando, **not the values**. If the values were held weakly we'd have weak-references, which we don't. The idea is this: if some object is used as a key in the Expando, this object can be CGed. Will then be automatically removed from the Expando (together with its value) as soon as it is CGed.

I should use a map only to hold the key types like null/numbers/strings/booleans which can't be used as keys in the Expando, because they are never CGed anyway.

I will check again the code today, but it's impossible to create tests for it, because Dart hides the CG too well.

**Comment by mraleph** [comment]
Yeah, my statement "On the other hand values are held weakly through the expando." is incorrect, brain fart.

As the code is written right now in `WeakMap` neither keys nor values are garbage collected.

**Comment by marcglasberg** [comment]
See version 1.1.0. It should be fixed. But as I said, I can't test, so I depend on people here to check the code. So it would be nice if you could recheck the code. Thanks.

**Comment by mraleph** [comment]
Yeah now it looks correct. 

FWIW there is a way to test it - but it is a bit gnarly: you can use Dart C API to create actual weak references, so you can use that to track lifetime of objects.

**Comment by marcglasberg** [comment]
Thanks for the tip. I'll have a look into the Dart C API.
